name: $name
main: nl.onlyfour.openminetopia.OpenMinetopia
version: $version
api-version: $apiVersion
description: $description
authors:
  - OnlyF0uR
load: POSTWORLD
depend:
  - Vault
  - WorldEdit
  - WorldGuard
softdepend:
  - PlaceholderAPI
commands:
  pin:
    description: "Pin command"
    usage: "/pin <player> <amount>"